import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Separator } from "@/components/ui/separator";

const Privacy = () => {
  return (
    <div className="min-h-screen bg-white">
      <Navbar />

      <main className="pt-24 pb-16">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-8">
            <h1 className="text-4xl font-bold text-gray-900">Privacy Policy</h1>
            <p className="mt-2 text-gray-600">Last Updated: May 3, 2025</p>
          </div>

          <div className="prose max-w-none">
            <p className="text-gray-600">
              AdLoot ("we," "our," or "us") is committed to protecting your
              privacy. This Privacy Policy explains how your personal
              information is collected, used, and disclosed by AdLoot. This
              Privacy Policy applies to our website, and its associated
              subdomains (collectively, our "Service") alongside our
              application, AdLoot. By accessing or using our Service, you
              signify that you have read, understood, and agree to our
              collection, storage, use, and disclosure of your personal
              information as described in this Privacy Policy and our Terms of
              Service.
            </p>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">
              Definitions and Key Terms
            </h2>
            <p className="text-gray-600">
              To help explain things as clearly as possible in this Privacy
              Policy, every time any of these terms are referenced, are strictly
              defined as:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-600">
              <li>
                Cookie: small amount of data generated by a website and saved by
                your web browser. It is used to identify your browser, provide
                analytics, remember information about you such as your language
                preference or login information.
              </li>
              <li>
                Company: when this policy mentions "Company," "we," "us," or
                "our," it refers to AdLoot, that is responsible for your
                information under this Privacy Policy.
              </li>
              <li>
                Country: where AdLoot or the owners/founders of AdLoot are
                based, in this case is United States
              </li>
              <li>
                Customer: refers to the company, organization or person that
                signs up to use the AdLoot Service to manage the relationships
                with your consumers or service users.
              </li>
              <li>
                Device: any internet connected device such as a phone, tablet,
                computer or any other device that can be used to visit AdLoot
                and use the services.
              </li>
              <li>
                Service: refers to the services provided by AdLoot as described
                in the relative terms (if available) and on this platform.
              </li>
              <li>
                Personal Data: any information that directly, indirectly, or in
                connection with other information — including a personal
                identification number — allows for the identification or
                identifiability of a natural person.
              </li>
              <li>
                Usage Data: refers to data collected automatically either
                generated by the use of the Service or from the Service
                infrastructure itself (for example, the duration of a page
                visit).
              </li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">
              Information We Collect
            </h2>
            <p className="text-gray-600">
              We collect several different types of information for various
              purposes to provide and improve our Service to you.
            </p>

            <h3 className="text-xl font-bold text-gray-900 mt-6 mb-2">
              Types of Data Collected:
            </h3>

            <h4 className="text-lg font-bold text-gray-900 mt-4 mb-2">
              Personal Data
            </h4>
            <p className="text-gray-600">
              While using our Service, we may ask you to provide us with certain
              personally identifiable information that can be used to contact or
              identify you ("Personal Data"). Personally identifiable
              information may include, but is not limited to:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-600">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>Phone number</li>
              <li>Address, State, Province, ZIP/Postal code, City</li>
              <li>Cookies and Usage Data</li>
            </ul>

            <h4 className="text-lg font-bold text-gray-900 mt-4 mb-2">
              Usage Data
            </h4>
            <p className="text-gray-600">
              We may also collect information that your browser sends whenever
              you visit our Service or when you access the Service by or through
              a mobile device ("Usage Data"). This Usage Data may include
              information such as your computer's Internet Protocol address
              (e.g. IP address), browser type, browser version, the pages of our
              Service that you visit, the time and date of your visit, the time
              spent on those pages, unique device identifiers and other
              diagnostic data.
            </p>

            <Separator className="my-8" />

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">
              How We Use Your Information
            </h2>
            <p className="text-gray-600">
              We use the information we collect or receive:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-600">
              <li>To provide and maintain our Service;</li>
              <li>To notify you about changes to our Service;</li>
              <li>
                To allow you to participate in interactive features of our
                Service when you choose to do so;
              </li>
              <li>To provide customer support;</li>
              <li>
                To gather analysis or valuable information so that we can
                improve our Service;
              </li>
              <li>To monitor the usage of our Service;</li>
              <li>To detect, prevent and address technical issues;</li>
              <li>To fulfill any other purpose for which you provide it;</li>
              <li>
                To carry out our obligations and enforce our rights arising from
                any contracts entered into between you and us, including for
                billing and collection;
              </li>
              <li>
                To provide you with notices about your account and/or
                subscription, including expiration and renewal notices,
                email-instructions, etc.;
              </li>
            </ul>

            <Separator className="my-8" />

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">
              Disclosure of Data
            </h2>

            <h3 className="text-xl font-bold text-gray-900 mt-6 mb-2">
              Disclosure for Law Enforcement
            </h3>
            <p className="text-gray-600">
              Under certain circumstances, AdLoot may be required to disclose
              your Personal Data if required to do so by law or in response to
              valid requests by public authorities (e.g. a court or a government
              agency).
            </p>

            <h3 className="text-xl font-bold text-gray-900 mt-6 mb-2">
              Legal Requirements
            </h3>
            <p className="text-gray-600">
              AdLoot may disclose your Personal Data in the good faith belief
              that such action is necessary to:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-600">
              <li>To comply with a legal obligation</li>
              <li>To protect and defend the rights or property of AdLoot</li>
              <li>
                To prevent or investigate possible wrongdoing in connection with
                the Service
              </li>
              <li>
                To protect the personal safety of users of the Service or the
                public
              </li>
              <li>To protect against legal liability</li>
            </ul>

            <Separator className="my-8" />

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">
              Security of Data
            </h2>
            <p className="text-gray-600">
              The security of your data is important to us, but remember that no
              method of transmission over the Internet, or method of electronic
              storage is 100% secure. While we strive to use commercially
              acceptable means to protect your Personal Data, we cannot
              guarantee its absolute security.
            </p>

            <Separator className="my-8" />

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">
              Your Data Protection Rights
            </h2>
            <p className="text-gray-600">
              We would like to make sure you are fully aware of all of your data
              protection rights. Every user is entitled to the following:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-600">
              <li>
                <span className="font-semibold">The right to access</span> – You
                have the right to request copies of your personal data.
              </li>
              <li>
                <span className="font-semibold">
                  The right to rectification
                </span>{" "}
                – You have the right to request that we correct any information
                you believe is inaccurate. You also have the right to request
                that we complete the information you believe is incomplete.
              </li>
              <li>
                <span className="font-semibold">The right to erasure</span> –
                You have the right to request that we erase your personal data,
                under certain conditions.
              </li>
              <li>
                <span className="font-semibold">
                  The right to restrict processing
                </span>{" "}
                – You have the right to request that we restrict the processing
                of your personal data, under certain conditions.
              </li>
              <li>
                <span className="font-semibold">
                  The right to object to processing
                </span>{" "}
                – You have the right to object to our processing of your
                personal data, under certain conditions.
              </li>
              <li>
                <span className="font-semibold">
                  The right to data portability
                </span>{" "}
                – You have the right to request that we transfer the data that
                we have collected to another organization, or directly to you,
                under certain conditions.
              </li>
            </ul>

            <h2 className="text-2xl font-bold text-gray-900 mt-8 mb-4">
              Contact Us
            </h2>
            <p className="text-gray-600">
              If you have any questions about this Privacy Policy, please
              contact us:
            </p>
            <ul className="list-disc pl-6 mb-4 text-gray-600">
              <li>By email: info@adloot.io</li>
              <li>
                By visiting this page on our website: www.adloot.io/contact
              </li>
              <li>By phone number: +212626556963</li>
            </ul>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Privacy;
